FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq
RUN apt-get upgrade -y

RUN apt-get install -yqq --no-install-recommends \
	build-essential \
    git \
    automake

RUN apt-get install -yqq --no-install-recommends \
	ca-certificates \
&& update-ca-certificates 2>/dev/null || true

RUN apt-get install -yqq --no-install-recommends \
	curl sqlite

# Download Go and install it to /usr/local/go
RUN curl -s https://golang.org/dl/go1.16.linux-amd64.tar.gz | tar -v -C /usr/local -xz

# Let's people find our Go binaries
ENV PATH $PATH:/usr/local/go/bin

# RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags "-extldflags -static" -o /out/xlsxcli .

### ----------------------
### https://docs.docker.com/develop/develop-images/multistage-build/

### FROM golang:1.7.3 AS builder
### WORKDIR /go/src/github.com/alexellis/href-counter/
### RUN go get -d -v golang.org/x/net/html  
### COPY app.go    .
### RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
### 
### FROM alpine:latest  
### RUN apk --no-cache add ca-certificates
### WORKDIR /root/
### COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
### CMD ["./app"]  


### $ docker build --target builder -t alexellis2/href-counter:latest .